version: "3.7" 
services:
  nginx:
    image: nginx:1.17.3
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - "./index.php:/var/www/html/public"
      - "./nginx.conf:/etc/nginx"
    links:
      - php
      - mysql

  php:
    build:
      context: .
    image: phpdocker
    container_name: php
    ports:
      - "9000:9000"
  

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3307:3306"
    volumes:
      - mysql:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: 'finalprojectdb'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '654321'
      MYSQL_ROOT_PASSWORD: '6543'
volumes:
  mysql: